global:
  resolve_timeout: 30s
  smtp_smarthost: 'localhost:25'
  smtp_from: 'no-reply@localhost'
  slack_api_url: 'url'
templates:
#- /var/moniter/alertmanager/slack.tmpl
- /var/moniter/alertmanager/notifications.tmpl
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 60m
  receiver: 'slack_alerts_channel'    
  routes: 
  - match:
      severity: 'warning'
    receiver: 'slack_alerts_channel'
  - match:
      severity: 'critical'
    receiver: 'slack_alerts_channel'
  - match:
      severity: 'websiteDown'
    receiver: 'email_managers'
receivers:
- name: 'slack_alerts_channel'
  slack_configs:
  - send_resolved: true
    channel: '#general'
#    title: '{{ template "custom_title" . }}'
#    text: '{{ template "custom_slack_message" . }}'
    title: '{{ .Status | toUpper }}{{ if eq .Status "firing" }} - {{ .Alerts.Firing | len }}{{ end }} | TENDERCUTS PROMETHEUS ALERTS'
    text: >-
      {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *State:* `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
        *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}

- name: 'email_managers'
  email_configs:
  - to: 'xyz@gmail.com'
    require_tls: false
    send_resolved: true
