global:
  scrape_interval:     20s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 20s # Evaluate rules every 15 seconds. The default is every 1 minute.
  
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels: 
          instance: Prometheus

  - job_name: 'linux systems'
    static_configs:
      - targets: ['localhost:9100']
        labels: 
          instance: mlops
      - targets: ['192.168.0.111:9100']
        labels: 
          instance: puppetserver
  - job_name: 'MySQL'
    static_configs:
      - targets: ['192.168.0.111:9104']
        labels: 
          instance: puppetserver
  - job_name: 'blackbox'
    scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://127.0.0.1   # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
